let list2=["Ahmad ", "Qamar", "Abdullah"];
console.log("Hi, "+ list2[0]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[1]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[2]+ " I would like to invite you to dinner!");
console.log(list2[1]+ " cant make it! ");
list2.splice(1,1,"Ali");
console.log("Hi, "+ list2[0]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[1]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[2]+ " I would like to invite you to dinner!");
console.log("I just found a bigger table!");
list2.unshift("Awais");
list2.splice(list2.length/2,0,"Sufiyan");
list2.push("Wahab");
console.log("Hi, "+ list2[0]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[1]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[2]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[3]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[4]+ " I would like to invite you to dinner!");
console.log("Hi, "+ list2[5]+ " I would like to invite you to dinner!");